### ISSUE TITLE
OLS Estimator in bvar_fn.m

### ISSUE THREAD

**Issue by Marianojgm86** [tcaravello/varplus#1]
Hi, I'm checking your codes and I have a quick question.

In the bvar_fn.m function, when you are defining the posteriors for the Reduced-Form Parameters you define: 

```
OomegaTilde         = (X'*X  + OomegaBarInverse)\eye(m);
OomegaTildeInverse  =  X'*X  + OomegaBarInverse;
PpsiTilde           = OomegaTilde*(X'*Y + OomegaBarInverse*PpsiBar);
```

and then use the PpsiTilde as the OLS Estimator, if I'm correct. 

But this calculation yields:
`PpsiTilde = (X'X)*(X'Y) ` (since the other thigs are zeros) 

If this is the OLS Estimator, shouldn't this calculation be:
`PpsiTilde = inv(X'X)*(X'Y)`? 

I'm not sure if it changes somenthing further.

Thanks!

**Comment by tcaravello** [comment]
Hi!

Thanks for your message. The original code is correct: note that the line
OomegaTilde = (X'*X + OomegaBarInverse)\eye(m); effectively sets
OomegaTilde = (X'*X)^(-1) (since A\B = A^(-1)*B) so the estimator has the
form you describe.

Tomás

**Comment by Marianojgm86** [comment]
Thanks Tomas!
